"""Generate PBS job scripts matching this project's HPC conventions
(see Z:/test_runs_tours/code/job_sa_bandit.pbs for the reference pattern):
module-load Anaconda3, conda activate, editable-install-or-pip-fallback for
MetaCount/SearchLibrium, JAX forced to CPU, single-threaded BLAS.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class PbsConfig:
    job_name: str
    script_filename: str          # the generated *.py to execute, e.g. "run_search.py"
    ncpus: int = 4
    mem_gb: int = 32
    walltime: str = "24:00:00"
    conda_env: str = "zigenv"
    hpc_metacount_src: str = "/mnt/hpccs01/home/ahernz/source/MetaCount"
    hpc_searchlibrium_src: str = "/mnt/hpccs01/home/ahernz/source/SearchLibrium"
    extra_env: dict = field(default_factory=dict)
    email_events: str = "abe"     # abort/begin/end notifications


_PKG_INSTALL_BLOCK = r'''
# ── Install MetaCount + SearchLibrium (editable source; skip if already linked) ──
_HPC_MC={hpc_metacount_src}
_HPC_SL={hpc_searchlibrium_src}

_pkg_needs_install() {{
    local pkg="$1" src_dir="$2"
    if ! python -c "import $pkg" 2>/dev/null; then return 0; fi
    if [ -n "$src_dir" ] && [ -d "$src_dir" ]; then
        local loc
        loc=$(python -c "import $pkg, os; print(os.path.dirname($pkg.__file__))" 2>/dev/null || echo "")
        [[ "$loc" != "$src_dir"* ]] && return 0
    fi
    return 1
}}

echo "[pkg] Checking MetaCount..."
if [ -d "$_HPC_MC" ]; then
    if _pkg_needs_install metacountregressor "$_HPC_MC"; then
        pip install -e "$_HPC_MC" -q && echo "[pkg] MetaCount installed (editable: $_HPC_MC)"
    else
        echo "[pkg] MetaCount already installed (editable) — skipping"
    fi
else
    if _pkg_needs_install metacountregressor ""; then
        pip install --no-cache-dir -q metacountregressor && echo "[pkg] MetaCount installed (PyPI)"
    else
        echo "[pkg] MetaCount already installed — skipping"
    fi
fi

echo "[pkg] Checking jax/jaxlib/jaxopt..."
if ! python -c "import jax, jaxlib, jaxopt" 2>/dev/null; then
    pip install --no-cache-dir -q jax jaxlib jaxopt && echo "[pkg] jax/jaxlib/jaxopt installed"
else
    echo "[pkg] jax/jaxlib/jaxopt already installed — skipping"
fi

echo "[pkg] Checking SearchLibrium..."
if [ -d "$_HPC_SL" ]; then
    if _pkg_needs_install SearchLibrium "$_HPC_SL"; then
        pip install -e "$_HPC_SL" -q && echo "[pkg] SearchLibrium installed (editable: $_HPC_SL)"
    else
        echo "[pkg] SearchLibrium already installed (editable) — skipping"
    fi
else
    if _pkg_needs_install SearchLibrium ""; then
        pip install --no-cache-dir -q SearchLibrium && echo "[pkg] SearchLibrium installed (PyPI)"
    else
        echo "[pkg] SearchLibrium already installed — skipping"
    fi
fi

echo "[pkg] Package versions:"
pip show metacountregressor 2>/dev/null | awk '/^Name:|^Version:/{{print "  " $0}}' || true
pip show SearchLibrium      2>/dev/null | awk '/^Name:|^Version:/{{print "  " $0}}' || true
'''


def generate_pbs_script(cfg: PbsConfig) -> str:
    env_lines = "\n".join(f'export {k}="{v}"' for k, v in cfg.extra_env.items())
    pkg_block = _PKG_INSTALL_BLOCK.format(
        hpc_metacount_src=cfg.hpc_metacount_src,
        hpc_searchlibrium_src=cfg.hpc_searchlibrium_src,
    )

    return f'''#!/bin/bash -l
# Auto-generated by ModelZoo GUI — {cfg.job_name}
#
# Submit with:  qsub {cfg.job_name}.pbs
# Monitor with: qstat -u $USER

#PBS -N {cfg.job_name}
#PBS -l select=1:ncpus={cfg.ncpus}:mem={cfg.mem_gb}GB
#PBS -l walltime={cfg.walltime}
#PBS -j oe
#PBS -m {cfg.email_events}
#PBS -r y

cd "$PBS_O_WORKDIR"

module purge
module load Anaconda3/2024.02-1
conda activate "{cfg.conda_env}"
module unload Anaconda3
{pkg_block}
# ── Runtime env ──────────────────────────────────────────────────────────────
export JAX_PLATFORMS=cpu
export TF_CPP_MIN_LOG_LEVEL=3
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
{env_lines}

echo "=========================================="
echo "PBS job     : ${{PBS_JOBID:-unknown}}"
echo "Working dir : $PBS_O_WORKDIR"
echo "Started     : $(date)"
echo "=========================================="

stdbuf -oL python -u {cfg.script_filename}
EXIT_CODE=$?

echo "=========================================="
echo "Finished : $(date)  exit_code=${{EXIT_CODE}}"
echo "=========================================="
exit "$EXIT_CODE"
'''
