"""Auto-generated by ModelZoo GUI — SearchLibrium search run: e2e_smoke

Run locally:
    python run_searchlibrium.py

The dashboard SearchLibrium prints at the end of the run is the primary
report; this script also writes a small JSON summary to results/.
"""
import json
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("JAX_PLATFORMS", "cpu")
# PYTHONIOENCODING only takes effect if set before the interpreter starts, so
# also reconfigure stdout/stderr directly — SearchLibrium's dashboard prints
# box-drawing Unicode that crashes on Windows' default cp1252 console.
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import numpy as np
import pandas as pd
from SearchLibrium import Parameters, call_search

print("=" * 70)
print("SearchLibrium run: e2e_smoke")
print("=" * 70)

t0 = time.time()
df = pd.read_csv('c:\\Users\\ahernz\\source\\ModelZoo\\generated_jobs\\_e2e_test\\choice_data.csv')
print(f"Loaded data: {df.shape[0]} rows x {df.shape[1]} cols from 'c:\\Users\\ahernz\\source\\ModelZoo\\generated_jobs\\_e2e_test\\choice_data.csv'")

choice_set = np.unique(df['alt']).tolist()

params = Parameters(
    criterions   = [('bic', -1)],
    df           = df,
    varnames     = ['TIME', 'COST'],
    asvarnames   = ['TIME', 'COST'],
    isvarnames   = [],
    choice_set   = choice_set,
    choices      = df['CHOICE'].values,
    alt_var      = df['alt'].values,
    choice_id    = df['custom_id'].values,
    ind_id      = None,
    base_alt     = '1',
    models       = ['multinomial'],
    allow_random = False,
    allow_bcvars = False,
    allow_corvars= False,
    n_draws      = 50,
    maxiter      = 100,
    p_val        = 0.05,
    
)

print("\nRunning search (algorithm='sa')...")
best = call_search(params, algorithm='sa', id_num=1)

elapsed = time.time() - t0
print(f"\nSearch finished in {elapsed:.1f}s")

out_dir = Path('results')
out_dir.mkdir(parents=True, exist_ok=True)
summary = {
    "experiment_name": 'e2e_smoke',
    "algorithm": 'sa',
    "models": ['multinomial'],
    "elapsed_seconds": elapsed,
    "best_repr": repr(best),
}
out_path = out_dir / ('e2e_smoke' + "_summary.json")
out_path.write_text(json.dumps(summary, indent=2, default=str))
print(f"Saved run summary to {out_path}")
