"""Auto-generated by ModelZoo GUI — metacountregressor search run: e2e_mc_smoke

Run locally:
    python run_metacount.py
"""
import os
import sys
os.environ.setdefault("JAX_PLATFORMS", "cpu")
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
sys.stderr.reconfigure(encoding="utf-8", errors="replace")

import time
import pandas as pd
from metacountregressor import (
    ExperimentBuilder,
    ModelConstraints,
    SearchOutputConfig,
    extract_search_best,
    extract_summary,
)

print("=" * 70)
print("metacountregressor run: e2e_mc_smoke")
print("=" * 70)

t0 = time.time()
from metacountregressor import load_example16_3_model_data
df = load_example16_3_model_data()
print(f"Loaded data: {df.shape[0]} rows x {df.shape[1]} cols")

constraints = (
    ModelConstraints()
    .force_include('OFFSET')
    .no_random('URB')
)
print(constraints)

builder = ExperimentBuilder(
    df=df,
    id_col='ID',
    y_col='FREQ',
    offset_col='OFFSET',
    
)
try:
    builder.describe()
except Exception as e:
    # describe() is diagnostic-only; some upstream metacountregressor versions
    # crash on non-numeric columns outside `variables` (e.g. label columns).
    print(f"[warn] builder.describe() failed, continuing without it: {e}")

evaluator = builder.build_count_evaluator(
    variables=['AADT', 'LENGTH', 'SPEED', 'CURVES'],
    constraints=constraints,
    
    default_roles=[0, 1, 2, 3],
    max_latent_classes=1,
    R=50,
)

output_config = SearchOutputConfig(
    output_dir='results',
    experiment_name='e2e_mc_smoke',
    search_description='smoke test',
    save_json=True,
)

print("\nRunning search (algo='sa')...")
result = builder.run(
    evaluator,
    algo='sa',
    max_iter=30,
    seed=42,
    output_config=output_config,
)

elapsed = time.time() - t0
best = extract_search_best(result)
print(f"\nSearch finished in {elapsed:.1f}s")
print("Best BIC:", best["best_bic"])
print("Saved to:", result.get("saved_to"))

print("\nRefitting best structure with R=50...")
best_spec = evaluator.build_spec(best["best_decision"])
fit = builder.fit_manual_model(manual_spec=best_spec, model='nb', R=50)
summary = extract_summary(fit)
print("\nFinal fit summary:")
for k, v in summary.items():
    print(f"  {k:>10}: {v}")
